name: Check and test

on:
  push:
    branches: ["main", "release/candidate"]
  pull_request:

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python:
          - "3.10" # minimum required
          - "3.13"
          - "3.14" # latest
        include:
          - python: "3.10"
            os: windows-latest
          - python: "3.10"
            os: macos-latest

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.python == '3.14' }}
    permissions:
      contents: read
      checks: write
    env:
      UV_PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          version: "0.11.x"
          enable-cache: false
      - run: uv sync
      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run pyright --warnings
      - run: uv run pytest
      - run: uv run coverage xml
      - uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        if: >
          (github.event_name == 'pull_request' || github.ref_name == 'main') &&
          matrix.python == '3.10' &&
          matrix.os == 'ubuntu-latest'
        with:
          # Ignore .coverage, which has limited support from coveralls
          file: coverage.xml

  build-beets-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        beets:
          - "git+https://github.com/beetbox/beets#master"
          - "beets==2.4.*"
          - "beets==2.5.*"
          - "beets==2.6.*"
          - "beets==2.7.*"
          - "beets==2.8.*"
          - "beets==2.9.*"
          - "beets==2.10.*"
          - "beets==2.11.*"
    env:
      UV_PYTHON: "3.10"

    continue-on-error: ${{ contains(matrix.beets, 'master') }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          enable-cache: false
      - run: uv add ${{ matrix.beets }}
      - run: uv sync
      - run: uv run pytest
